project:
  name: "GoMiler"
  state: "unstable"
  image: ""
  website: ""
  oneLiner: "Milestone generation for platforms including GitLab and GitHub"
  description: |
    Generate milestone for ToDo lists, sprints or more.
  version: "v0.2.0"
  mainLicense: "apache2"
  docsLicense: "CCBySa"

vision:
  type: "community"
  overview: |
    Milestone generation for platforms including GitLab and GitHub.
readme:
  usageExample: |
    ```
    go get -u -v https://github.com/okkur/gomiler/...
    gomiler -namespace=yournamespace  -project=yourproject -token=123456789 -url=devhub.example.com
    ```

    For more information about flags:      
    ```
    gomiler --help
    ```

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/gomiler/labels/starter%20issue"

emails:
  commercialSupport: "support@okkur.io"
  security: "security@okkur.io"
  coc: "coc@okkur.io"

copyright:
  year: "2017"

cla:
  copyrightHolder: "Michael Grosser"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"
  - name: "Adeel Hussain"
    nick: "adeilh"
  - name: "David Briesz"
    nick: "dbriesz"

repo:
  link: "https://github.com/okkur/gomiler/"
  type: "Github"

badges:
  - image: "https://img.shields.io/badge/state-stable-green.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/okkur/gomiler.svg"
    link: "https://github.com/okkur/gomiler/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/okkur/gomiler.svg"
    link: "LICENSE"
    alt: "license"
