project:
  name: "GoMiler"
  state: "unstable"
  image: ""
  website: ""
  oneLiner: "Easy milestone creation for your favorite project tracking website"
  description: |
    Generate one milestone per day\week\month within your Gitlab project.
    Use for your Gitlab based ToDo list or sprints.
  version: "v0.1.0"
  mainLicense: "apache2"
  docsLicense: "CCBySa"

vision:
  type: "community"
  overview: |
    Simple daily milestone generation for Gitlab.

readme:
  usageExample: |
  
    git clone https://github.com/okkur/gomiler.git

    go get -u github.com/peterhellberg/link

    cd gomiler

    go build main.go

    ./main -advance=10 -namespace=gitnamespace  -project=gitproject -token=123456789 -url=some.thing.eu  -interval=weekly

    or

    go run main.go --advance=10 --namespace=gitnamespace  --project=gitproject --token=123456789 --url=some.thing.eu  --interval=weekly

    flags:

    advance: Define timeframe

    namespace: Gitlab/Github Namespace

    project: Gitlab/Github Project Namespace

    token: Gitlab/Github token generated by Gitlab

    baseurl: Gitlab/Github api Base URL

    timeinterval: Daily/Weekly/Monthly   

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/okkur/dailymile/labels/starter%20issue" # replace dear-github with your actual url

emails:
  commercialSupport: "support@okkur.io"
  security: "security@okkur.io"
  coc: "coc@okkur.io"

copyright:
  year: "2017"

cla:
  copyrightHolder: "Michael Grosser"

maintainers:
  - name: "Adeel Hussain"
    nick: "adeilh"
  - name: "Michael Grosser"
    nick: "stp-ip"
  - name: "David Riesz"
    nick: "dbriesz"
  - name: "Erfan Besharat"
    nick: "erbesharat"    

repo:
  link: "https://github.com/okkur/dailymile/"
  type: "Github"

badges:
  - image: "https://img.shields.io/badge/state-unstable-blue.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/okkur/dailymile.svg"
    link: "https://github.com/okkur/dailymile/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/okkur/dailymile.svg"
    link: "LICENSE"
    alt: "license"
